### ISSUE TITLE
Location of reference sequence prefix

### ISSUE THREAD

**Issue by jjfarrell** [citiususc/BigBWA#3]
I am unclear on what type of file system the  reference index belongs on for the index parameter....

-index - the index prefix is specified. The index must be available in all the cluster nodes at the same location.

For the index file that is used by BigBWA, is that stored on an HDFS file system, local file system or mounted nfs system?

**Comment by jmabuin** [comment]
Hi jjfarrell,

the reference index can be stored locally in each one of the nodes, for example in the /opt/ folder, or you can have it located in one of the nodes and share it by using NFS.

The important thing here is that the location needs to be the same, because all of BigBWA maps are going to search the index in the same local location.
